version: "3.8"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend:ro
      - ./backend:/app:ro
    environment:
      - DATABASE_URL=sqlite:///./backend.db
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - web
    restart: unless-stopped
